# Generated by Django 5.2.6 on 2025-09-18 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_notification_followcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='is_featured',
            new_name='is_premium',
        ),
    ]
