# Generated by Django 5.2.1 on 2025-09-23 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_rename_is_featured_audio_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stories.category'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stories.audio'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(),
        ),
    ]
